### PR TITLE
Automated javascript code examples

### PR DESCRIPTION
**Pull request by houbly**
Added automated code examples for js
Allows user to toggle between ES6 and browser compatible js in the code example

### CODE REVIEW

**Review by gldgrnt — APPROVED** [review]
This looks very nice!

**Comment by gldgrnt** [comment]
Just a thought: would it be helpful to both the toggle options next to each other just so users know which is currently being showed?

image

**Comment by houbly** [comment]
> Just a thought: would it be helpful to show both the toggle options next to each other just so users know which is currently being showed?
> 
> image

I was considering this but I didn't see any existing styles for tabs e.g. active/inactive so this way just seemed easier. It does make more sense though. I think I will update it to use tabs and freestyle the active/inactive styles for now.

**Review by catiarodriguescosta — APPROVED** [review]
Good job @houbly! Looks good! :)

**Pull request merged**
