### PR TITLE
feat: The phrases nNetwork, nTicket, nTrain and nBus now show the 'n' as an SVG icon

### PR DESCRIPTION
**Pull request by daylesalmon**
This feature adds functionality to automatically replace phrases such as nBus with an icon + 'bus' as seen in the below screenshot.

image

However, there is one problem which will need addressing in future. Currently it replaces all innerHTMl within the body element...this strips out all eventListeners in the DOM, to avoid this for now I call the nIcon function before any other javascript runs to avoid it stripping event listeners.

In future, I will explore a way to target a specific class and just replace that only. The reason I haven't done that currently is because content editors don't have this ability in Umbraco (at the moment).

### CODE REVIEW

**Review by catiarodriguescosta — APPROVED** [review]
It looks really good! 👍

**Review by gldgrnt — CHANGES_REQUESTED** [review]
All good except for the typo on the scss variable `$width-mulitplier`

**Review by houbly — APPROVED** [review]

**Review by catiarodriguescosta — APPROVED** [review]
Looks good! 👍

**Review by gldgrnt — APPROVED** [review]
Great work

**Pull request merged**
