### PR TITLE
feat: add semantic release and versioning

### PR DESCRIPTION
**Pull request by gldgrnt**
Add semantic releases to the design system.

_Note: When this PR is merged the first version of the design system will be released_

### CODE REVIEW

**Review by houbly — DISMISSED** [review]
I can't see any syntax issues or anything, preview looks good

**Review by daylesalmon — CHANGES_REQUESTED** [review]
MicrosoftTeams-image
Almost there!

The links on the homepage should always be pointing to the latest version/release on unpkg.

**Review by catiarodriguescosta — DISMISSED** [review]

**Review by catiarodriguescosta — APPROVED** [review]
👍

**Review by houbly — APPROVED** [review]

**Pull request merged**
