### PR TITLE
feat: add ticket summary message component

### LINKED ISSUE #705: Add ticket summary page messages to Components in the Design System
# Documentation

## What does it do?

* The messages give an overall summary of what the ticket buyer can and cannot do, so they can understand the limits of the ticket they want to purchase

## How it works

* The relevant ticket messages appear on the ticket summary page below the full name and price of the ticket
* The You can and You cannot messages are shown on every ticket summary by default. You must and Swift card/photocard messages only appear if they are relevant to the chosen ticket

### You can

[insert You can message here]

### You cannot

[insert You cannot message here]

#### When to use it?
* If a ticket requires prerequisites for it to be valid, such as a photocard or if it requires a certain amount of people

[insert You must message here]

#### When to use it?
* When a ticket can be loaded onto a Swift card or Swift photocard
* This message must contain the terms and conditions for the relevant Swift card type

[insert You must message here]

### PR DESCRIPTION
**Pull request by gldgrnt**
Fixes #705

### CODE REVIEW

**Review by houbly — CHANGES_REQUESTED** [review]
Small thing, but I think you should include contentBefore/After ext/HTML in the njk example. Looks good otherwise.

**Review by jkmnch — CHANGES_REQUESTED** [review]
The You cannot and You must components are the wrong way round :)

**Review by jkmnch — APPROVED** [review]
Looks good :)

**Pull request merged**
