### PR TITLE
feat: In-text step documentation

### PR DESCRIPTION
**Pull request by houbly**
Documentation converted to markdown
Added Example.njk - for wmndsInTextStep
Updated Nunjucks components params - for wmndsInTextStep
Added properties for component params for wmndsInTextStep

### CODE REVIEW

**Review by catiarodriguescosta — APPROVED** [review]
Looking good! 👍

**Review by catiarodriguescosta — CHANGES_REQUESTED** [review]
Actually this won't accept HTML.. only text.. can we adjust it to receive HTML too as it could be needed?

**Review by catiarodriguescosta — APPROVED** [review]
Great work! 👍

**Review by daylesalmon — APPROVED** [review]

**Pull request merged**
