### PR TITLE
fix: changed ex units to em equivalent

### LINKED ISSUE #655: Bug with date input component
**Chrome 88 on Windows 10**

Screenshot 2021-02-16 at 15 00 53

### PR DESCRIPTION
**Pull request by houbly**
changed max width units from ex to em equivalent
fixes #655

### CODE REVIEW

**Review by daylesalmon — CHANGES_REQUESTED** [review]
Looks good, but declining as the branch is opened against master (not release).

**Review by daylesalmon — APPROVED** [review]
I've removed a few things that should be on the master branch only such as:
- changelog.md
- version number in package.json
- version number in packge-lock.json

**Review by catiarodriguescosta — APPROVED** [review]
👍

**Pull request merged**
