### PR TITLE
fix: update travel updates widget styling

### LINKED ISSUE #787: Travel updates widget: Needs smaller disruption indicators and reduced white space on mobile
## Disruption indicators

The current disruption indicator sizes are Medium. This widget will need to use the Small [disruption indicators](https://designsystem.wmnetwork.co.uk/components/disruption-indicators/) instead. Please update on both mobile and desktop. Also, please reduce white space between items to optimise it so users don't have to scroll too much. At the moment gaps are quite large. 

Screenshot 2021-05-20 at 12 53 14

Here are the designs if you need them: https://www.figma.com/file/rQRpNn6RM6nUcbm2HCWQlO/WMN-Design-System?node-id=0%3A5459

## Disruption link text

Mobile / break points

The disruption link text in the travel updates widget moves onto a new line when the screen size is 567px. This is an issue as there is still room for the disruption link text on the right side of the widget, so it makes the widget longer than it needs to be.

Since we will be using the smaller disruption indicators, the breakpoint for disruption link text will need to be changed when the screen size reaches 392px.

### PR DESCRIPTION
**Pull request by houbly**
- Changed disruption indicators to displayNarrow
- minor styling amendments to disruption indicator and delete button
fixes #787

### CODE REVIEW

**Review by jkmnch — COMMENTED** [review]
Hey Houston,

What's the mobile breakpoint for this widget?

**Review by gldgrnt — DISMISSED** [review]
Looks great from a dev perspective

**Comment by houbly** [comment]
> Hey Houston,
> 
> What's the mobile breakpoint for this widget?

It's the sm breakpoint

**Comment by catiarodriguescosta** [comment]
> > Hey Houston,
> > What's the mobile breakpoint for this widget?
> 
> It's the sm breakpoint

768px

**Comment by jkmnch** [comment]
Is it possible to change the mobile breakpoint for this widget to 392px?

This is because there's loads of white space available when the disruption links can still fit on the right side.

Screenshot 2021-06-03 at 09 02 46

**Review by catiarodriguescosta — APPROVED** [review]
Looks good! 👍

**Comment by jkmnch** [comment]
That's much better :) Thanks

**Review by gldgrnt — APPROVED** [review]
👍🏾

**Pull request merged**
