### PR TITLE
feat: Adding transport modals to branded banner

### LINKED ISSUE #832: Add purple branded banner variant
## What

> Add variant of purple branded banner where transport modals are visible.

(originally requested here: https://github.com/wmcadigital/wmn-cms/issues/214 )

## Anything else

https://www.figma.com/file/PDLwmCZgpcrI6hfIHKYLku/New-Swift-Custom-Pages?node-id=135%3A0

### PR DESCRIPTION
**Pull request by catiarodriguescosta**
Fix #832 
Design page link: https://www.figma.com/file/PDLwmCZgpcrI6hfIHKYLku/New-Swift-Custom-Pages?node-id=515%3A373

### CODE REVIEW

**Review by jkmnch — COMMENTED** [review]
Hey Catia, can the transport mode icons with their text move onto the next line when the screen size is smaller?

**Review by jkmnch — APPROVED** [review]
Looks great 👍

**Review by gldgrnt — APPROVED** [review]
Nice 👍🏾

**Pull request merged**
