### PR TITLE
Mega menu search feature

### LINKED ISSUE #441: Add documentation for each Search pattern element into the new 'Search' page, under Patterns in the Design System.
### About

**What does it do?**
* Allows the user to search for information across the West Midlands Network website

**When to use it?**
* When a user needs to find the information they need, which they cannot find through the main navigation

**How it works**
* Users should only be able to access the search function through the header by hovering or selecting the magnifying glass icon
* The search bar will appear in a dropdown along with the ‘I want to…’ feature, where users can access popular search queries
* Once a user submits their search query, they will be able to view the search results. They can sort and filter the search results on the search results page

### Search bar

> Insert search bar pattern

### Sort

**What does it do?**
* This gives the user the option to sort search results by relevance or when a page was last updated

> Insert sort pattern

### Filter

**What does it do?**
* This gives the user the option to filter search results using a predetermined set of filters

**How it works**
* The filters will narrow down the search results by displaying pages which only match the filter criteria
* On mobile, the filter options will appear when a user clicks on the ‘Filter your results button’. This will trigger an overlay where users can select and apply filters. This is to reduce page size on smaller devices

> Insert filter collapsed/expanded pattern

### Search result

**What does it do?**
* This is how a matching page will display in the search results page

**How it works**
* Each page result will show the page breadcrumbs on desktop. On mobile, breadcrumbs are not shown. This is to reduce page size on smaller devices
* The page description will display main body copy which is highest on the page. The description will be a maximum of 150 characters. Any descriptions longer than 150 characters will be truncated.
* If the user’s search query is in the page description, it will be highlighted in bold. This is to help them understand the context of the page
* The horizontal rule at the bottom of a search result is to make the results list easier to scan.

> Insert search result pattern

### Pagination links

**What does it do?**
* Allows the user to navigate through search results.

> Insert pagination patterns

### LINKED ISSUE #461: Header pattern - display bug on hover - Safari 14.0
**Describe the bug**
Active state for header 1st level items is a couple of pixels down on Safari 14.0

Screenshot 2020-10-22 at 08 58 34

### LINKED ISSUE #462: Header pattern: Megamenu doesn't hide when a user's keyboard focus moves onto the main body content.
**Describe the bug**
When a user moves keyboard focus from the last link in the Get Help section, the keyboard focus moves onto the link in the body content, but the megamenu is still shown on the screen and doesn't disappear.

**Expected behaviour**
When a user clicks on tab after the last link the header (Report a problem with a shelter or stop), then the megamenu should disappear when the keyboard focus moves to links in the body content.

**Screenshots**
Screenshot 2020-10-22 at 09 14 45

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: 86.0.4240.80

**Additional context**
- There is an issue in Safari where the header turns black when the keyboard focus moves from the last link in the header into the main body content. I'll post this as a separate issue.

### LINKED ISSUE #465: Header pattern: Add a hover delay to each menu dropdown.
**Describe the bug**
We should add a hover delay to the menu options to avoid flickering and to stop users from triggering a different menu option when they move their cursor in a diagonal line to reach a Level 2 link in the far left column.

See this quote from Baymard Institute:
>But to avoid the “fickering of hover-based drop-down navigation itself, you’ll need to introduce a hover delay – a minimum amount of time the user has to hover the trigger area before the drop-down content appears. Typically a delay of 300–500 milliseconds will suffice in eliminating the worst “fickering" without introducing needless friction for intentional hover interactions.

**Expected behaviour**
A hover delay of 300–500 milliseconds should be implemented to avoid flickering and prevent accidental hovering over other trigger areas.

**Examples of websites which use this**
- https://www.johnlewis.com/
- https://www.adidas.co.uk/
- https://www.asos.com/men/

**Additional context**
The full Baymard Institute article on intelligent hover systems goes into this in more detail:
[Consider Having a _Drop-Down_ Menu, Ide...ategory - Guidelines - Baymard Premium.pdf](https://github.com/wmcadigital/wmn-design-system/files/5421714/Consider.Having.a._Drop-Down_.Menu.Ide.ategory.-.Guidelines.-.Baymard.Premium.pdf)

Unfortunately, you need a paid account to view the web link so I've exported a PDF for you. I still have access from my previous employer 🤫

### PR DESCRIPTION
**Pull request by houbly**
Added search feature to mega menu header
Includes fixes #441, fixes #461, fixes #462, fixes #465

### CODE REVIEW

**Review by catiarodriguescosta — APPROVED** [review]
Looks good to me! 👍

**Review by daylesalmon — APPROVED** [review]

**Review by catiarodriguescosta — APPROVED** [review]
👍

**Review by gldgrnt — APPROVED** [review]
👍🏾

**Review by jkmnch — CHANGES_REQUESTED** [review]
Looking great! Just a couple of accessibility issues I've seen:

- The tab order should go down the left column of links first and then move onto the right column after.
- When using the tab button, a user can't use the directional buttons to move keyboard focus left, right, up and down in the 'I want to...' links, like in the other navigation options.
- I'm not sure if this is possible or not, but once I use the tab button after the last link in the search menu, the dropdown still appears on the desktop and doesn't disappear when I move keyboard focus onto links in the main content/footer.

Other than that, I think it's ready to go 👍

**Comment by houbly** [comment]
> Looking great! Just a couple of accessibility issues I've seen:
> 
> * The tab order should go down the left column of links first and then move onto the right column after.
> * When using the tab button, a user can't use the directional buttons to move keyboard focus left, right, up and down in the 'I want to...' links, like in the other navigation options.
> * I'm not sure if this is possible or not, but once I use the tab button after the last link in the search menu, the dropdown still appears on the desktop and doesn't disappear when I move keyboard focus onto links in the main content/footer.
> 
> Other than that, I think it's ready to go 👍

@jkmnch I'm addressing these changes in another branch so this pull request isn't too big.

**Review by jkmnch — APPROVED** [review]

**Pull request merged**
