### PR TITLE
feat: Add timetable patterns

### LINKED ISSUE #870: Timetables for Stop/Station pages
Add a new page named **Timetables** under **Patterns**.

The designs for the homepage widgets can be found in the Homepage page in the Figma DS: https://www.figma.com/file/rQRpNn6RM6nUcbm2HCWQlO/TfWM-Design-System?node-id=612%3A2699

# Timetables
### What does it do?
* Shows the full timetable for a bus service or tram service

### When to use it?
* On a bus stop or tram stop page

### How it works?
* Selecting a departure time will display the full route of the bus or tram service from that time
* Users can choose a day of the week, including bank holidays
* The [Warning text](https://designsystem.tfwm.org.uk/components/warning-text/) component informs users when the timetable was last updated and if there is an upcoming change to the timetable
* Users can download a PDF file of the timetable 
* Users can see the service route page for a bus or tram by selecting the ‘View full route’ button

#### Default

[show default timetable]

#### Departure time selected

[show expanded timetable with time selected]

### What does it do?
* Directs users to the train operator(s) website so they can view full timetables
* Helps users to find which train operator(s) run services between two rail stations

### When to use it?
* On a train station page

### How it works?
* Users enter their departure and arrival station
* The results will tell users which operator(s) run services between the two rail stations and link them to the train operator(s) homepage

#### Default

[show default train timetable search]

#### Results

[show train timetable search results]

### What does it do?
* Shows the full route for a bus or tram service

### When to use it?
* On a bus or tram service route page

### How it works?
* Users can view bus or tram stop pages by selecting the link

[show route pattern]

### PR DESCRIPTION
**Pull request by houbly**
- Added timetable patterns for find a timetable service
- Includes patterns for:
-- Bus and tram timetable
-- Train timetable
-- Bus and tram route
fixes #870

### CODE REVIEW

**Review by jkmnch — CHANGES_REQUESTED** [review]
Hi Houston,

The expanded view window showing the next bus stops will need to have a set height, rather than showing all of the stops from the selected time, like how it currently works on the stop pages: https://legacy.wmnetwork.co.uk/plan-your-journey/stops/detail/#/stop=43000702303?operator=NXB&service=16&version=0&when=0&time=1540

**Comment by houbly** [comment]
> Hi Houston,
> 
> The expanded view window showing the next bus stops will need to have a set height, rather than showing all of the stops from the selected time, like how it currently works on the stop pages: https://legacy.wmnetwork.co.uk/plan-your-journey/stops/detail/#/stop=43000702303?operator=NXB&service=16&version=0&when=0&time=1540

@jkmnch Okay that's fine, I'm assuming the close button should be fixed to the top when scrolled?

**Comment by jkmnch** [comment]
@houbly Yes please

**Review by jkmnch — APPROVED** [review]
Looks great!

**Review by gldgrnt — APPROVED** [review]
Looks really good

**Pull request merged**
