### PR TITLE
Vertically align Accordion titles

### LINKED ISSUE #412: Accordion titles should be vertically aligned to the +/- toggle icons.
**Describe the bug**
Currently, the Accordion component titles are fixed to the top, rather than in the middle.

**Expected behavior**
An Accordion title needs to be horizontally aligned to the +/- buttons.

**Screenshots**

Before:
Screenshot 2020-09-15 at 11 08 13

After:
Screenshot 2020-09-15 at 12 35 58

**Additional context**
Correct designs are in Zeplin, if needed.

### PR DESCRIPTION
**Pull request by gldgrnt**
Fixes #412

### CODE REVIEW

**Review by catiarodriguescosta — APPROVED** [review]
👍

**Review by houbly — APPROVED** [review]
All good

**Review by houbly — CHANGES_REQUESTED** [review]
looks fine but you could remove the `float: right` on the icon

**Review by houbly — APPROVED** [review]

**Review by catiarodriguescosta — APPROVED** [review]
Looks good!

**Pull request merged**
