### PR TITLE
Contact details pattern

### LINKED ISSUE #310: Create Contact details pattern
Create Contact details pattern and add it to Design system on Netlify. 

All components are listed in Zeplin Styleguides https://app.zeplin.io/styleguide/5d95b0aaad77af16c796a476/components?coid=5f3a7b7fe11ed48072fe78ce 

- [ ] Contact details address
- [ ] Contact details template
- [ ] Contact details template with warning icon
- [ ] Contact details TfWM boilerplate

### PR DESCRIPTION
**Pull request by catiarodriguescosta**
Reusing inset text component.

Fixes #310

### CODE REVIEW

**Review by gldgrnt — CHANGES_REQUESTED** [review]
All good except a couple of minor things, a comment and [2 typos](https://github.com/wmcadigital/wmn-design-system/pull/336/checks?check_run_id=1020903917).

**Comment by gldgrnt** [comment]
Also is there anything that can be done about the indentation on the previews:

image

**Review by houbly — CHANGES_REQUESTED** [review]
Can you do something about the spacing between new lines? It looks more compact in the styleguide.
Also there are a couple of typos flagged on the word 'Midlands'

Design system
Screenshot 2020-08-24 at 11 27 09

Styleguide
Screenshot 2020-08-24 at 11 27 30

**Review by houbly — APPROVED** [review]

**Review by gldgrnt — APPROVED** [review]
Looks good to me

**Pull request merged**
