### PR TITLE
fix: update heading modifier classes

### LINKED ISSUE #651: Make heading modifier classes identical to heading styles
**Describe the bug**
Heading modifier classes don't include font family and colour styles so when used they can sometimes look inconsistent.

**Expected behavior**
Styles need to be added to the modifier classes (`.h1, .h2, .h3` etc) which are identical to the styles on the heading elements `h1, h2, h3`

### PR DESCRIPTION
**Pull request by houbly**
Changed heading modifier classes to include colour and font family styles. Fixes #651

### CODE REVIEW

**Review by gldgrnt — APPROVED** [review]
👍🏾

**Review by gldgrnt — CHANGES_REQUESTED** [review]
This changes the colour of the heading in the footer

image

**Review by daylesalmon — DISMISSED** [review]

**Review by daylesalmon — CHANGES_REQUESTED** [review]
As @gldgrnt has mentioned, the colours in the footer are wrong.
It may be worth doing a global find for all .h1,h1, .h2,h2 .h3,h3.... classes via scss and double check where they are used and that they are showing as expected.

**Review by daylesalmon — APPROVED** [review]

**Review by gldgrnt — APPROVED** [review]
👍🏾

**Pull request merged**
