### PR TITLE
Fix background extension of footer.

### LINKED ISSUE #304: Header and footer page - footer code example is all black background
Screenshot 2020-08-19 at 09 00 07

### PR DESCRIPTION
**Pull request by catiarodriguescosta**
Fixes #304

### CODE REVIEW

**Review by gldgrnt — COMMENTED** [review]
This has the following effect on the footer on the site itself. I don't know whether it's what we want though lol

Before:
image

After:
image

**Comment by catiarodriguescosta** [comment]
> This has the following effect on the footer on the site itself. I don't know whether it's what we want though lol

@gldgrnt I was about to ask you why you add that, here's the question. As my page was full, I didn't find any trouble. :/

**Comment by gldgrnt** [comment]
> @gldgrnt I was about to ask you why you add that, here's the question. As my page was full, I didn't find any trouble. :/

@catiarodriguescosta Yeah I'm looking on a large screen, so was just pointing out that the shadow doesn't extend to the bottom anymore. The fix is fine, it just depends on if we / people are happy with the change ☺️

**Comment by catiarodriguescosta** [comment]
> > @gldgrnt I was about to ask you why you add that, here's the question. As my page was full, I didn't find any trouble. :/
> 
> @catiarodriguescosta Yeah I'm looking on a large screen, so was just pointing out that the shadow doesn't extend to the bottom anymore. The fix is fine, it just depends on if we / people are happy with the change ☺️

@mrmjprice and @daylesalmon what do you think? Could it be a problem?

**Comment by daylesalmon** [comment]
I'd recommend leaving it as the "before" as it doesn't display nice on larger screens.
We need to have a look at how the component-example works and make sure the shadow doesn't overflow into the code snippet area. 

So i'd focus efforts there rather than the component itself.

**Comment by mrmjprice** [comment]
Ah - I see the problem now!

We definitely need the footer CSS to remain the same, else short pages (especially apps that are loading) look really weird.

Is there anything we can do to make it work okay within the example on the design system?

**Review by gldgrnt — APPROVED** [review]
Nice

**Review by houbly — APPROVED** [review]

**Pull request merged**
